function augmentedData = augmentData(data)
    imageAugmenter = imageDataAugmenter( ...
        'RandRotation',[-20,20], ...
        'RandXReflection',true, ...
        'RandScale',[0.8,1.2]);
    augmentedData = augmentedImageDatastore([224 224], data, 'DataAugmentation', imageAugmenter);
end
